### ISSUE TITLE
sysadmin dashboard - phase 1: Address any python3 issues

### ISSUE THREAD

**Issue by briangrossman** [mitodl/edx-platform#191]
Address any python3 issues with the sysadmin panel

**Comment by pdpinch** [comment]
There was some discussion on the Build, Test, Release call that there are python3 issues with the current code, possibly related to strings. I'm trying to confirm that.

**Comment by arslanashraf7** [comment]
> There was some discussion on the Build, Test, Release call that there are python3 issues with the current code, possibly related to strings. I'm trying to confirm that.

@pdpinch I did test the python3 changes on the sysadmin dashboard and below are my findings:

Most of the things seem to be working fine except for the below issue.

**Issue**
Found an issue (`TypeError: string argument expected, got 'bytes'`) with functionalities `Download list of all users (csv file)` & `Download staff & instructor list (csv file)`. 

Source reference for the method causing issue: https://github.com/edx/edx-platform/blob/dbe96cff8cdb2f1187c3b021f2365253e7caf98d/lms/djangoapps/dashboard/sysadmin.py#L74

**Solution:** As a solution we could use `BytesIO` instead of `StringIO` for `unicodecsv package` that's currently being used for creating csv but, **Since we are already removing these functionalities in [This PR](https://github.com/edx/edx-platform/pull/25474/files)**, I think we might not need to change/add a fix for it.

**Note:**
Initially, it doesn't seem to be related to python3, But I'm currently facing some issues with **mongo db connection refusal** in `git course import ` & `git logs` so these two are not tested yet with python3. I'll try to get these running and add further details here.

**Comment by pdpinch** [comment]
Thanks @arslanashraf7. 

Regarding the issues with `Download staff and instructor list` we are debating between [Umar's PR #25474](https://github.com/edx/edx-platform/pull/25474) which removes the functionality and https://github.com/edx/edx-platform/pull/25093 which fixes it.  

Regarding mongo connections, @blarghmatey has a couple of commits in our Juniper branch that address this: 41811d7dea and 4f8ce2db17. I've opened a separate issue (https://github.com/mitodl/edx-platform/issues/194) for addressing this, since edX probably won't accept it upstream.

**Comment by arslanashraf7** [comment]
> Thanks @arslanashraf7.
> 
> Regarding the issues with `Download staff and instructor list` we are debating between [Umar's PR #25474](https://github.com/edx/edx-platform/pull/25474) which removes the functionality and [edx#25093](https://github.com/edx/edx-platform/pull/25093) which fixes it.
> 
> Regarding mongo connections, @blarghmatey has a couple of commits in our Juniper branch that address this: [41811d7](https://github.com/mitodl/edx-platform/commit/41811d7deaf7892ab8916dbbb8f7636eca4c63ca) and [4f8ce2d](https://github.com/mitodl/edx-platform/commit/4f8ce2db1714b54f6964ccfde76c1ed8f1744a16). I've opened a separate issue (#194) for addressing this, since edX probably won't accept it upstream.

Thanks for the details.
This fix [edx#25093](https://github.com/edx/edx-platform/pull/25093) looks fine to me as well.
For mongo connections, I'll have a look at the aforementioned suggestions.

**Comment by arslanashraf7** [comment]
@pdpinch I was able to run `mongodb` locally and tested `Load new course from Github` and `git logs` functionality on sysadmin dashboard and both of these seem to work fine with python3 as well.

**Just in case:** The solutions that worked and might come in handy for fixing `ServerSelectionTimeoutError : localhost:27017: [Errno 111] Connection refused` on local setup are:

1. Open `/lms/envs/devstack.py` and add `MONGODB_LOG = {"host": “<Mongo Container’s ID or Name or IP>”}`
2. Alternatively, open `docker-compose.yml` and add `--bind_ip localhost` in mongo container's command, This overrides the default configuration of mongo. (Be mindful of your mongo container’s name here. e.g. `edx.devstack.mongo`)
