### ISSUE TITLE
Maple: cherry-pick rapid response commits

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#273]
[Rapid Response xBlock](https://github.com/mitodl/rapid-response-xblock) is an xBlock aside that we deploy with the residential platform that adds real-time charting to multiple-choice problems. It's used in synchronous courses at MIT. 

- [ ] review the code in bbe7d0628d and determine what of it is necessary to support the xblock (the commit is quite messy)
- [ ] if possible, upstream the necessary code
- [ ] if not possible to upstream, create a plugin in https://github.com/mitodl/open-edx-plugins if possible
- [ ] if neither of those options work, open a PR on the mitx/maple branch with the needed code

**Comment by pdpinch** [comment]
There may be some useful information in https://github.com/mitodl/rapid-response-xblock/issues/79

**Comment by arslanashraf7** [comment]
**Update:**

While working on this ticket and looking through the commit(s) we've been cherry-picking (https://github.com/mitodl/edx-platform/commit/bbe7d0628d2f4f0800406f18b65d066525f766ce) I saw some inconsistencies which I'm going to list down below for the sake of posterity:
- We've been cherry-picking a chunk of code([this](https://github.com/mitodl/edx-platform/commit/bbe7d0628d2f4f0800406f18b65d066525f766ce#diff-2e708ec7862cbe8e9fe138f4cde50b224d98e95f958dfc645b5ab76075035d8dR1072-R1208) & [this](https://github.com/mitodl/edx-platform/commit/bbe7d0628d2f4f0800406f18b65d066525f766ce#diff-2e708ec7862cbe8e9fe138f4cde50b224d98e95f958dfc645b5ab76075035d8dR1499-R1828)) that was actually once a part of edX and was removed in a [PR](https://github.com/edx/edx-platform/commit/a0f24bbb64a3889f4073d95f9e517d1309139e1d#diff-2e708ec7862cbe8e9fe138f4cde50b224d98e95f958dfc645b5ab76075035d8d) some time ago but since our commits had that code in them from past cherry-picks so we somehow kept on carrying that code ahead thinking we need it.
- At some point when we cherry-picked(https://github.com/mitodl/edx-platform/issues/254) we had to fix some import errors in other files (`Canvas Integration & Remote Gradebook`) to make the platform work and those changes became part of the commit.
- We've created our own [CSV generation function](https://github.com/mitodl/edx-platform/commit/bbe7d0628d2f4f0800406f18b65d066525f766ce#diff-2e708ec7862cbe8e9fe138f4cde50b224d98e95f958dfc645b5ab76075035d8dR3532) but there is a possibility that we can refactor that and use [this utility csv function](https://github.com/edx/edx-platform/blob/3152c14192dcccac79b7b7a76eba91b380eba78a/lms/djangoapps/instructor_analytics/csvs.py#L13) from the platform.

All the above points fixed/being fixed can be seen in this PR (https://github.com/mitodl/edx-platform/pull/275)

**_A Question/Clarification:_** There is another ticket about refactoring download reports (https://github.com/mitodl/open-edx-plugins/issues/9) and the commits mentioned in that have been a part of the cherry-pick we have been doing for rapid response. And I believe both this ticket &  https://github.com/mitodl/edx-platform/pull/275 are interdependent and can/should be done in a single cycle & single plugin once created. Is my assumption correct?

FYI, @pdpinch

**Comment by pdpinch** [comment]
Yes I agree that these can all be addressed in one PR for the plug-in. Thank you for catching that. 

> I believe both this ticket & #275 are interdependent and can/should be done in a single cycle & single plugin once created. Is my assumption correct?

**Comment by arslanashraf7** [comment]
Closed via https://github.com/mitodl/open-edx-plugins/pull/17 & https://github.com/mitodl/open-edx-plugins/pull/17
